app/jwc/__init__.py
from flask import Blueprint

jwc = Blueprint('jwc', __name__)

from . import views

app/jwc/views.py
from flask import render_template, request, redirect, url_for, g, make_response, jsonify
from .. import rdb
from ..utils import hmget_decode
from . import jwc, function
import json


@jwc.before_request
def before_request():
    if request.endpoint not in ['jwc.login', 'jwc.verify']:
        if 'JWCCOOKIE' not in request.cookies or not rdb.exists('jwc:' + request.cookies['JWCCOOKIE']):
            return redirect(url_for('.login'))
        g.cookie = request.cookies['JWCCOOKIE']
        g.name = 'jwc:' + g.cookie


@jwc.route('/')
def index():
    years, terms, selected_year, selected_term, table = hmget_decode(
        rdb, g.name, ['years', 'terms', 'selected_year', 'selected_term', 'table'])
    if None in (years, terms, selected_year, selected_term, table):
        years, terms, selected_year, selected_term, table = function.init_schedule(g.cookie)
    return render_template('jwc.html', table=table, years=years.split(','), terms=terms.split(','),
                           selected_year=selected_year, selected_term=selected_term)


@jwc.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        if 'JWCCOOKIE' in request.cookies and rdb.exists('jwc:' + request.cookies['JWCCOOKIE']):
            return redirect(url_for('.index'))
        return render_template('login.html', entry='教务处')
    else:
        username = request.form['username']
        password = request.form['password']
        code = request.form['code']
        if not username.strip() or not password.strip() or not code.strip():
            return render_template('login.html', entry='教务处', msg='帐号/密码/验证码为空')
        cookie = request.cookies.get('JWCCOOKIE')
        msg = function.login(username, password, code, cookie)
        if msg:
            return render_template('login.html', entry='教务处', msg=msg)
        return redirect(url_for('.index'))


@jwc.route('/code')
def verify():
    content, cookie = function.get_code()
    resp = make_response(content)
    resp.set_cookie('JWCCOOKIE', cookie)
    resp.mimetype = 'image/gif'
    return resp


@jwc.route('/score', methods=['POST'])
def score():
    year = request.form['year']
    term = request.form['term']
    items = function.get_score(g.cookie, year, term)
    total, gpa, credit = [], [], []
    for item in items:
        total.append(int(item['total']))
        gpa.append(float(item['gpa']))
        credit.append(float(item['credit']))
    info = None
    if items:
        info = {
            'sum': sum(credit),
            'max': max(total),
            'min': min(total),
            'ave': round(sum([c * p for c, p in zip(credit, gpa)]) / sum(credit), 2)
        }
    return jsonify({
        'items': items,
        'info': info
    })


@jwc.route('/schedule', methods=['POST'])
def schedule():
    year = request.form['year']
    term = request.form['term']
    table = function.get_schedule(g.cookie, year, term)
    return jsonify({
        'table': table
    })

app/library/__init__.py
from flask import Blueprint

library = Blueprint('library', __name__)

from . import views

app/library/views.py
from flask import render_template, request, redirect, url_for, g, make_response, jsonify
from .. import rdb
from ..utils import hmget_decode
from . import library, function


@library.before_request
def before_request():
    if  request.endpoint not in ['library.login', 'library.verify']:
        if 'LIBCOOKIE' not in request.cookies or not rdb.exists('lib:' + request.cookies['LIBCOOKIE']):
            return redirect(url_for('.login'))
        g.cookie = request.cookies['LIBCOOKIE']


@library.route('/')
def index():
    keys = ['name', 'identifier', 'type', 'unit']
    values = hmget_decode(rdb, 'lib:' + g.cookie, keys)
    if None in values:
        info = function.get_info(g.cookie)
    else:
        info = dict(zip(keys, values))
    books = function.get_books(g.cookie)
    return render_template('library.html', books=books, info=info)


@library.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        if 'LIBCOOKIE' in request.cookies and rdb.exists('lib:' + request.cookies['LIBCOOKIE']):
            return redirect(url_for('.index'))
        return render_template('login.html', entry='图书馆')
    username = request.form['username']
    password = request.form['password']
    code = request.form['code']
    if not username.strip() or not password.strip() or not code.strip():
        return render_template('login.html', entry='图书馆', msg='帐号/密码/验证码为空')
    cookie = request.cookies.get('LIBCOOKIE')
    msg = function.login(cookie, username, password, code)
    if msg != '登录成功':
        return render_template('login.html', entry='图书馆', msg=msg)
    resp = make_response(redirect(url_for('.index')))
    return resp


@library.route('/code')
def verify():
    content, cookie = function.get_code()
    resp = make_response(content)
    resp.set_cookie('LIBCOOKIE', cookie)
    resp.mimetype = 'image/jpeg'
    return resp


@library.route('/renew_code')
def renew_verify():
    content = function.get_renew_code(g.cookie)
    resp = make_response(content)
    resp.mimetype = 'image/jpeg'
    return resp


@library.route('/renew')
def renew():
    barcode = request.args.get('barcode', None)
    code = request.args.get('code', None)
    check = request.args.get('check', None)
    if not code:
        return jsonify({'success': False, 'msg': '验证码不能为空'})
    elif not barcode or not check:
        return jsonify({'success': False, 'msg': '未知错误'})
    msg = function.renew(g.cookie, barcode, code, check)
    if '成功' in msg:
        return jsonify({'success': True})
    return jsonify({'success': False, 'msg': msg})


@library.route('/logout')
def logout():
    rdb.delete('lib:' + g.cookie)
    return redirect(url_for('.login'))

app/scholat/__init__.py
from flask import Blueprint

scholat = Blueprint('scholat', __name__)

from . import views

app/scholat/views.py
from flask import render_template, request, redirect, url_for, g, make_response, abort, jsonify
from .. import rdb
from ..utils import hget_decode
from . import scholat, function
import json


@scholat.before_request
def before_request():
    if not request.endpoint == 'scholat.login':
        if 'SCHCOOKIE' not in request.cookies or not rdb.exists('sch:' + request.cookies['SCHCOOKIE']):
            return redirect(url_for('.login'))
        g.cookie = request.cookies['SCHCOOKIE']
        g.name = 'sch:' + g.cookie


@scholat.route('/')
def index():
    courses = hget_decode(rdb, g.name, 'courses')
    if not courses:
        courses = function.get_courses(g.cookie)
    else:
        courses = json.loads(courses)
    return render_template('scholat.html', courses=courses, info=None)


@scholat.route('/course/<int:cid>')
@scholat.route('/course/<int:cid>/<int:cur>')
def course(cid, cur=1):
    courses = hget_decode(rdb, g.name, 'courses')
    if not courses:
        courses = function.get_courses(g.cookie)
    else:
        courses = json.loads(courses)
    info = hget_decode(rdb, g.name, 'info:' + str(cid))
    if not info:
        info = function.get_info(g.cookie, cid)
    else:
        info = json.loads(info)
    items, info['page'], info['sid'] = function.get_homework(g.cookie, cid, cur)
    info['cid'], info['cur'] = cid, cur
    return render_template('scholat.html', courses=courses, homework=items, info=info)


@scholat.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        if 'SCHCOOKIE' in request.cookies and rdb.exists('sch:' + request.cookies['SCHCOOKIE']):
            return redirect(url_for('.index'))
        return render_template('login.html', entry='学者网')
    username = request.form['username']
    password = request.form['password']
    if not username.strip() or not password.strip():
        return render_template('login.html', entry='学者网', msg='帐号/密码为空')
    msg, cookie = function.login(username, password)
    if not cookie:
        return render_template('login.html', entry='学者网', msg=msg)
    resp = make_response(redirect(url_for('.index')))
    resp.set_cookie('SCHCOOKIE', cookie)
    return resp


@scholat.route('/logout')
def logout():
    rdb.delete(g.name)
    return redirect(url_for('.login'))


@scholat.route('/homework')
def homework():
    cid = request.args.get('cid', None)
    sid = request.args.get('sid', None)
    hid = request.args.get('hid', None)
    if not cid or not sid or not hid:
        abort(404)
    content, hdr = function.download_homework(g.cookie, cid, sid, hid)
    if not content:
        abort(404)
    resp = make_response(content)
    resp.headers['Content-Disposition'] = hdr['Content-Disposition']
    resp.headers['Content-Type'] = hdr['Content-Type']
    resp.headers['Connection'] = 'Keep-Alive'
    return resp


@scholat.route('/details')
def details():
    cid = request.args.get('cid', None)
    hid = request.args.get('hid', None)
    if not cid or not hid:
        abort(404)
    content, items = function.get_details(g.cookie, cid, hid)
    if not content:
        abort(404)
    footer = [{
        'url': url_for('.attach', cid=cid, lid=item['lid']),
        'title': item['title']
    } for item in items]
    return jsonify({
        'content': content,
        'footer': footer
    })


@scholat.route('/attach')
def attach():
    cid = request.args.get('cid', None)
    lid = request.args.get('lid', None)
    if not cid or not lid:
        abort(404)
    content, hdr = function.download_attach(g.cookie, cid, lid)
    if not content:
        abort(404)
    resp = make_response(content)
    resp.headers['Content-Disposition'] = hdr['Content-Disposition']
    resp.headers['Content-Type'] = hdr['Content-Type']
    resp.headers['Connection'] = 'Keep-Alive'
    return resp


@scholat.route('/upload', methods=['POST'])
def upload():
    file = request.files['file']
    cid = request.form['cid']
    sid = request.form['sid']
    hid = request.form['hid']
    rs = function.upload_homework(g.cookie, cid, sid, hid, file.stream, file.filename)
    return 'success' if rs else 'failed'

app/score/__init__.py
from flask import Blueprint

score = Blueprint('score', __name__)

from . import views

app/score/views.py
from flask import render_template, request, redirect, url_for, g, make_response, jsonify
from .. import rdb
from ..utils import hmget_decode
from . import score, function
import json


@score.before_request
def before_request():
    if request.endpoint not in ['score.login', 'score.verify']:
        if 'SCOCOOKIE' not in request.cookies or not rdb.exists('sco:' + request.cookies['SCOCOOKIE']):
            return redirect(url_for('.login'))
        g.cookie = request.cookies['SCOCOOKIE']
        g.name = 'sco:' + g.cookie


@score.route('/')
def index():
    info, terms = hmget_decode(rdb, g.name, ['info', 'terms'])
    return render_template('score.html', info=json.loads(info), terms=json.loads(terms))


@score.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        if 'SCOCOOKIE' in request.cookies and rdb.exists('sco:' + request.cookies['SCOCOOKIE']):
            return redirect(url_for('.index'))
        return render_template('login.html', entry='校园网')
    else:
        username = request.form['username']
        password = request.form['password']
        code = request.form['code']
        if not username.strip() or not password.strip() or not code.strip():
            return render_template('login.html', entry='校园网', msg='帐号/密码/验证码为空')
        cookie = request.cookies.get('SCOCOOKIE')
        if not function.check(cookie, code):
            return render_template('login.html', entry='校园网', msg='验证码错误')
        cookie = function.login(cookie, username, password, code)
        if not cookie:
            return render_template('login.html', entry='校园网', msg='用户名或密码错误')
        resp = make_response(redirect(url_for('.index')))
        resp.set_cookie('SCOCOOKIE', cookie)
        return resp


@score.route('/code')
def verify():
    content, cookie = function.get_code()
    resp = make_response(content)
    resp.set_cookie('SCOCOOKIE', cookie)
    resp.mimetype = 'image/jpeg'
    return resp


@score.route('/get', methods=['POST'])
def get():
    year = request.form['year']
    term = request.form['term']
    info, items = function.get_score(g.cookie, year, term)
    return jsonify({
        'info': info,
        'items': items
    })


@score.route('/logout')
def logout():
    rdb.delete(g.name)
    return redirect(url_for('.login'))

app/templates/index.html
{% extends "layout.html" %}
{% block body %}
<!-- 介绍屏幕 -->
<div class="jumbotron">
    <div class="container">
        <h1>欢迎使用 SCNU Service</h1>
        <br />
        <p>本平台主要拥有以下功能</p>
        <ul>
            <li><p>查询学者网的作业信息</p></li>
            <li><p>查询图书馆的借阅信息</p></li>
            <li><p>查询教务系统的成绩信息</p></li>
        </ul>
    </div>
</div>
{% endblock %}

app/templates/jwc.html
{% extends "layout.html" %}
{% block body %}
<div id="success-alert" class="alert alert-success alert-hidden">获取成功！</div>
<div id="fail-alert" class="alert alert-danger alert-hidden">获取失败！</div>
<div class="container" style="padding-top: 40px;">
    <!-- 内容导航条 -->
    <ul class="nav nav-tabs">
        <li><a href="#schedule" data-toggle="tab">课表查询</a></li>
        <li><a href="#score" data-toggle="tab">成绩查询</a></li>
    </ul>
    <div class="tab-content">
        <!-- 课表信息标签 -->
        <div class="tab-pane fade" id="schedule">
            <!-- 学年学期选择框 -->
            <div style="padding-top: 10px; width: 100%">
                <div class="input-group">
                    <span class="input-group-addon">学年</span>
                    <select id="year-schedule" class="form-control">
                    {% for year in years %}
                        {% if year == selected_year %}
                        <option value="{{ year }}" selected="selected">{{ year }}</option>
                        {% else %}
                        <option value="{{ year }}">{{ year }}</option>
                        {% endif %}
                    {% endfor %}
                    </select>
                    <span class="input-group-addon">学期</span>
                    <select id="term-schedule" class="form-control">
                    {% for term in terms %}
                        {% if term == selected_term %}
                        <option value="{{ term }}" selected="selected">{{ term }}</option>
                        {% else %}
                        <option value="{{ term }}">{{ term }}</option>
                        {% endif %}
                    {% endfor %}
                    </select>
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="button" onclick="load_schedule()">Go</button>
                    </div>
                </div>
            </div>
            <!-- 课表内容 -->
            <div id="content-schedule" style="padding-top: 10px; width: 100%">
                {{ table | safe }}
            </div>
        </div>
        <!-- 成绩信息标签 -->
        <div class="tab-pane fade" id="score">
            <!-- 学年学期选择框 -->
            <div style="padding-top: 10px; width: 100%">
                <div class="input-group">
                    <span class="input-group-addon">学年</span>
                    <select id="year-score" class="form-control">
                        {% for year in years %}
                        <option value="{{ year }}">{{ year }}</option>
                        {% endfor %}
                    </select>
                    <span class="input-group-addon">学期</span>
                    <select id="term-score" class="form-control">
                        {% for term in terms %}
                        <option value="{{ term }}">{{ term }}</option>
                        {% endfor %}
                    </select>
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="button" onclick="load_score()">Go</button>
                    </div>
                </div>
            </div>
            <!-- 成绩内容 -->
            <div style="padding-top: 10px; width: 100%">
                <table class="table">
                    <thead>
                        <tr>
                            <th>课程名称</th>
                            <th>学分</th>
                            <th>绩点</th>
                            <th>平时成绩</th>
                            <th>期末成绩</th>
                            <th>总成绩</th>
                        </tr>
                    </thead>
                    <tbody id="content-score">
                    </tbody>
                </table>
            </div>
            <!-- 成绩统计 -->
            <div style="padding-top: 10px; width: 50%">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">成绩统计</h3>
                    </div>
                    <div id="info-score" class="panel-body">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var selected_year = "{{ selected_year }}";
    var selected_term = "{{ selected_term }}";
</script>
<script src="{{ url_for('static', filename='js/jwc.js') }}"></script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <title>SCNU Service</title>
        {% block static %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <script src="{{ url_for('static', filename='js/jquery-1.12.4.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        {% endblock %}
        {% block style %}
        <style type="text/css">
        body {
            padding-top: 50px;
        }
        .alert-hidden {
            display: none;
        }
        .label-align {
            padding-top: 3px;
            padding-bottom: 3px;
        }
        {% endblock %}
        </style>
    </head>
    <body>
        <!-- 顶部导航栏 -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a id="scnu-brand" class="navbar-brand" style="cursor: pointer;" onclick="account()">SCNU Service</a>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">首页</a></li>
                    <li><a href="{{ url_for('scholat.index') }}">学者网</a></li>
                    <li><a href="{{ url_for('library.index') }}">图书馆</a></li>
                    <li><a href="{{ url_for('score.index') }}">成绩查询</a></li>
                </ul>
            </div>
        </nav>
        {% block body %}{% endblock %}
        <!-- 帐号管理模态框 -->
        <div class="modal fade" id="account-modal" tabindex="-1">
            <div class="modal-dialog" >
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                        <h4>帐号管理</h4>
                    </div>
                    <div class="modal-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>帐号类型</th>
                                    <th>帐号状态</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>学者网</td>
                                    <td id="sch-status"></td>
                                    <td id="sch-operate"></td>
                                </tr>
                                <tr>
                                    <td>图书馆</td>
                                    <td id="lib-status"></td>
                                    <td id="lib-operate"></td>
                                </tr>
                                <tr>
                                    <td>成绩查询</td>
                                    <td id="sco-status"></td>
                                    <td id="sco-operate"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    </body>
</html>

app/templates/library.html
{% extends "layout.html" %}
{% block body %}
<script>var renew_verify_url = '{{ url_for('library.renew_verify') }}';</script>
<div id="success-alert" class="alert alert-success alert-hidden"><strong>续借成功！</strong></div>
<div id="fail-alert" class="alert alert-danger alert-hidden"></div>
<div class="container" style="padding-top: 40px">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">个人信息</h3>
        </div>
        <div class="panel-body">
            <p>读者姓名： {{ info.name }}</p>
            <p>读者号码： {{ info.identifier }}</p>
            <p>读者类型： {{ info.type }}</p>
            <p>工作单位： {{ info.unit }}</p>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>条码号</th>
                <th>题名</th>
                <th>责任者</th>
                <th>借阅日期</th>
                <th>应还日期</th>
                <th>续借量</th>
                <th>藏馆地</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{{ book.barcode }}</td>
                <td>{{ book.title | ellipsis }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.borrow }}</td>
                <td>{{ book.return }}</td>
                <td>{{ book.renew }}</td>
                <td>{{ book.place }}</td>
                <td>
                    <button type="button" class="btn btn-default btn-xs" onclick="show_verify('{{ book.barcode }}', '{{ book.check }}')">
                        <span class="glyphicon glyphicon-send"></span> 续借
                    </button>
                </td>
            </tr>
            {% else %}
            <tr>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<!-- 续借验证模态框 -->
<div class="modal fade" id="renew-verify" tabindex="-1">
    <div class="modal-dialog modal-sm" >
        <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4>请输入验证码</h4>
                </div>
                <div class="modal-body">
                    <input id="barcode" name="barcode" type="hidden">
                    <div class="input-group">
                        <input id="renew-input-code" type="text" class="form-control">
                        <span id="renew-get-code-group" class="input-group-btn">
                        </span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="renew-commit" class="btn btn-primary" onclick="renew()">续借</button>
                </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/library.js') }}"></script>
<script>
$(document).ready(function() {
    fresh_popover();
})
</script>
{% endblock %}

app/templates/login.html
{% extends "layout.html" %}
{% block body %}
<!-- 错误提示 -->
{% if msg %}
<div class="alert alert-danger alert-dismissible"><strong>登录失败！</strong>{{ msg }}</div>
{% endif %}
<!-- 登录界面 -->
<div class="container" style="width: 30%; padding-top: 60px">
    <form action="" method="post">
        <div class="form-group">
            <label>用户名</label>
            <input type="text" class="form-control" name="username" placeholder="输入{{ entry }}帐号">
        </div>
        <div class="form-group">
            <label>密码</label>
            <input type="password" class="form-control" name="password" placeholder="输入密码">
        </div>
        {% if entry in ('校园网', '教务处', '图书馆') %}
        <div class="form-group">
            <label>验证码</label>
            <div class="input-group">
                <input type="text" class="form-control" name="code" placeholder="输入验证码">
                <span class="input-group-btn">
                    <button id="btn-code" class="btn btn-default" type="button">获取验证码</button>
                </span>
            </div>
        </div>
        {% endif %}
        <br />
        <button id="btn-login" class="btn btn-primary btn-block" type="submit">登录</button>
        {% if entry in ('校园网', '教务处', '图书馆') %}
        <script>
            $(document).ready(function() {
                $("#btn-code").popover({
                    html : true,
                    placement : 'right',
                    {% if entry == '校园网' %}
                    content : '<img src="{{ url_for('score.verify') }}" />'
                    {% elif entry == '教务处' %}
                    content : '<img src="{{ url_for('jwc.verify') }}" />'
                    {% elif entry == '图书馆' %}
                    content : '<img src="{{ url_for('library.verify') }}">'
                    {% endif %}
                });
            })
        </script>
        {% endif %}
    </form>
</div>
{% endblock %}

app/templates/score.html
{% extends "layout.html" %}
{% block body %}
<div id="success-alert" class="alert alert-success alert-hidden">获取成功！</div>
<div id="fail-alert" class="alert alert-danger alert-hidden">获取失败！</div>
<div class="container" style="padding-top: 40px;">
    <!-- 内容导航条 -->
    <ul class="nav nav-tabs">
        <li><a href="#schedule" data-toggle="tab">个人信息</a></li>
        <li><a href="#score" data-toggle="tab">成绩查询</a></li>
    </ul>
    <div class="tab-content">
        <!-- 个人信息标签 -->
        <div class="tab-pane fade" id="schedule">
            <div style="padding-top: 10px;">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">个人信息</h3>
                    </div>
                    <div class="panel-body">
                        <p>姓名： {{ info.name }}</p>
                        <p>平均绩点： {{ info.points }}</p>
                        <p>本学期绩点： {{ info.currentTermPoints }}</p>
                        <p>未通过科目： {{ info.unPassCount }}</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- 成绩信息标签 -->
        <div class="tab-pane fade" id="score">
            <!-- 学年学期选择框 -->
            <div style="padding-top: 10px; width: 100%">
                <div class="input-group">
                    <span class="input-group-addon">学年 & 学期</span>
                    <select id="opt-score" class="form-control">
                        {% for term in terms %}
                        <option value="{{ term.year }}&{{ term.term }}">{{ term.year }} 学年第 {{ term.term }} 学期</option>
                        {% endfor %}
                    </select>
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="button" onclick="get_score()">Go</button>
                    </div>
                </div>
            </div>
            <!-- 成绩内容 -->
            <div style="padding-top: 10px; width: 100%">
                <table class="table">
                    <thead>
                        <tr>
                            <th>课程名称</th>
                            <th>学分</th>
                            <th>平时成绩</th>
                            <th>期末成绩</th>
                            <th>总成绩</th>
                        </tr>
                    </thead>
                    <tbody id="content-score">
                    </tbody>
                </table>
            </div>
            <!-- 成绩统计 -->
            <div style="padding-top: 10px; width: 50%">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">成绩统计</h3>
                    </div>
                    <div id="statistics-score" class="panel-body">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/score.js') }}"></script>
{% endblock %}